src/Entity/FicheFrais.php
<?php

namespace App\Entity;

use App\Repository\FicheFraisRepository;
use DateTime;
use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Exception;

#[ORM\Entity(repositoryClass: FicheFraisRepository::class)]
class FicheFrais
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?DateTimeInterface $mois = null;

    #[ORM\Column(nullable: true)]
    private ?int $nbJustificatifs = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 2, nullable: true)]
    private ?string $montantValid = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?DateTimeInterface $dateModif = null;

    #[ORM\ManyToOne(inversedBy: 'fichefrais')]
    private ?User $user = null;

    #[ORM\ManyToOne(inversedBy: 'fichesFrais')]
    private ?Etat $etat = null;

    /**
     * @var Collection<int, LigneFraisForfait>
     */
    #[ORM\OneToMany(targetEntity: LigneFraisForfait::class, mappedBy: 'fichesFrais', fetch: 'EAGER')]
    private Collection $lignefraisforfaits;

    /**
     * @var Collection<int, LigneFraisHorsForfait>
     */
    #[ORM\OneToMany(targetEntity: LigneFraisHorsForfait::class, mappedBy: 'fichesFrais', fetch: 'EAGER')]
    private Collection $lignesfraishorsforfait;

    public function __construct()
    {
        $this->lignefraisforfaits = new ArrayCollection();
        $this->lignesfraishorsforfait = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMois(): ?DateTimeInterface
    {
        return $this->mois;
    }

    public function setMois(DateTimeInterface $mois): static
    {
        $this->mois = $mois;

        return $this;
    }

    public function getNbJustificatifs(): ?int
    {
        return $this->nbJustificatifs;
    }

    public function setNbJustificatifs(?int $nbJustificatifs): static
    {
        $this->nbJustificatifs = $nbJustificatifs;

        return $this;
    }

    public function getMontantValid(): ?string
    {
        return $this->montantValid;
    }

    public function setMontantValid(?string $montantValid): static
    {
        $this->montantValid = $montantValid;

        return $this;
    }

    public function getDateModif(): ?DateTimeInterface
    {
        return $this->dateModif;
    }

    public function setDateModif(DateTimeInterface $dateModif): static
    {
        $this->dateModif = $dateModif;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    public function getEtat(): ?Etat
    {
        return $this->etat;
    }

    public function setEtat(?Etat $etat): static
    {
        $this->etat = $etat;

        return $this;
    }

    /**
     * @return Collection<int, LigneFraisForfait>
     */
    public function getLignefraisforfaits(): Collection
    {
        return $this->lignefraisforfaits;
    }

    public function addLignefraisforfait(LigneFraisForfait $lignefraisforfait): static
    {
        if (!$this->lignefraisforfaits->contains($lignefraisforfait)) {
            $this->lignefraisforfaits->add($lignefraisforfait);
            $lignefraisforfait->setFichesFrais($this);
        }

        return $this;
    }

    public function removeLignefraisforfait(LigneFraisForfait $lignefraisforfait): static
    {
        if ($this->lignefraisforfaits->removeElement($lignefraisforfait)) {
            // set the owning side to null (unless already changed)
            if ($lignefraisforfait->getFichesFrais() === $this) {
                $lignefraisforfait->setFichesFrais(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, LigneFraisHorsForfait>
     */
    public function getLignesfraishorsforfait(): Collection
    {
        return $this->lignesfraishorsforfait;
    }

    public function addLignesfraishorsforfait(LigneFraisHorsForfait $lignesfraishorsforfait): static
    {
        if (!$this->lignesfraishorsforfait->contains($lignesfraishorsforfait)) {
            $this->lignesfraishorsforfait->add($lignesfraishorsforfait);
            $lignesfraishorsforfait->setFichesFrais($this);
        }

        return $this;
    }

    public function removeLignesfraishorsforfait(LigneFraisHorsForfait $lignesfraishorsforfait): static
    {
        if ($this->lignesfraishorsforfait->removeElement($lignesfraishorsforfait)) {
            // set the owning side to null (unless already changed)
            if ($lignesfraishorsforfait->getFicheFrais() === $this) {
                $lignesfraishorsforfait->setFichesFrais(null);
            }
        }

        return $this;
    }

    public function setOldId($id)
    {
    }
}

src/Entity/LigneFraisForfait.php
<?php

namespace App\Entity;

use App\Repository\LigneFraisForfaitRepository;
use DateTimeInterface;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: LigneFraisForfaitRepository::class)]
class LigneFraisForfait
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    //#[ORM\Column(length: 255)]
    //private ?string $libelle = null;

    //#[ORM\Column(type: Types::DATE_MUTABLE)]
    //private ?DateTimeInterface $date = null;

   // #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 2)]
    //private ?string $montant = null;

    #[ORM\Column]
    private ?int $quantite = null;

    #[ORM\ManyToOne(inversedBy: 'lignefraisforfaits')]
    private ?FicheFrais $fichesFrais = null;

    #[ORM\ManyToOne(inversedBy: 'lignesFraisForfaits')]
    private ?FraisForfait $FraisForfaits = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    //public function getLibelle(): ?string
    //{
    //    return $this->libelle;
    //}

    //public function setLibelle(string $libelle): static
    //{
    //    $this->libelle = $libelle;

    //    return $this;
    //}

    //public function getDate(): ?DateTimeInterface
    //{
    //    return $this->date;
    //}

    //public function setDate(DateTimeInterface $date): static
    //{
    //    $this->date = $date;

    //    return $this;
    ///}

    //public function getMontant(): ?string
    //{
    //    return $this->montant;
    //}

    //public function setMontant(string $montant): static
    //{
    //    $this->montant = $montant;

    //    return $this;
    //}

    public function getQuantite(): ?int
    {
        return $this->quantite;
    }

    public function setQuantite(int $quantite): static
    {
        $this->quantite = $quantite;

        return $this;
    }

    public function getFichesFrais(): ?FicheFrais
    {
        return $this->fichesFrais;
    }

    public function setFichesFrais(?FicheFrais $fichesFrais): static
    {
        $this->fichesFrais = $fichesFrais;

        return $this;
    }

    public function getFraisForfaits(): ?FraisForfait
    {
        return $this->FraisForfaits;
    }

    public function setFraisForfaits(?FraisForfait $FraisForfaits): static
    {
        $this->FraisForfaits = $FraisForfaits;

        return $this;
    }

    public function getMontant(): ?string
    {
        if ($this->FraisForfaits) {
            return $this->FraisForfaits->getMontant() * $this->quantite;
        }
        return '0';
    }

    public function getFicheFrais()
    {
    }
}

src/Form/FicheFraisType.php
<?php

namespace App\Form;

use App\Entity\Etat;
use App\Entity\FicheFrais;
use App\Entity\User;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class FicheFraisType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('mois', null, [
                'widget' => 'single_text',
            ])
            ->add('nbJustificatifs')
            ->add('montantValid')
            ->add('dateModif', null, [
                'widget' => 'single_text',
            ])
            ->add('user', EntityType::class, [
                'class' => User::class,
                'choice_label' => 'id',
            ])
            ->add('etat', EntityType::class, [
                'class' => Etat::class,
                'choice_label' => 'id',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => FicheFrais::class,
        ]);
    }
}

src/Controller/FicheFraisController.php
<?php

namespace App\Controller;

use App\Entity\Etat;
use App\Entity\FicheFrais;
use App\Form\FicheFraisType;
use App\Form\MoisType;
use App\Repository\FicheFraisRepository;
use DateTime;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/fiche/frais')]
final class FicheFraisController extends AbstractController
{
    private EntityManagerInterface $entityManager;
    private FicheFraisRepository $ficheFraisRepository;

    public function __construct(EntityManagerInterface $entityManager, FicheFraisRepository $ficheFraisRepository)
    {
        $this->entityManager = $entityManager;
        $this->ficheFraisRepository = $ficheFraisRepository;
    }

    #[Route('/', name: 'app_fiche_frais_index', methods: ['GET', 'POST'])]
    public function index(Request $request): Response
    {
        $this->cloturerFichesFrais();
        $user = $this->getUser();
        $ficheFraisCollection = $this->ficheFraisRepository->findBy(['user' => $user]);

        $form = $this->createForm(MoisType::class, null, [
            'ficheFraisCollection' => $ficheFraisCollection, // Transmettre la collection des fiches de frais
        ]);

        $form->handleRequest($request);

        $selectedFicheFrais = null;
        $ligneFraisForfait = null;
        $ligneFraisHorsForfait = null;

        if ($form->isSubmitted() && $form->isValid()) {
            $ficheFraisId = $form->get('mois')->getData();
            if ($ficheFraisId) {
                $selectedFicheFrais = $this->ficheFraisRepository->find($ficheFraisId);
                $ligneFraisForfait = $selectedFicheFrais?->getLignefraisforfaits();
                $ligneFraisHorsForfait = $selectedFicheFrais?->getLignesfraishorsforfait();
            } else {
                $this->addFlash('error', 'Aucun mois sélectionné');
            }
        }

        return $this->render('fiche_frais/index.html.twig', [
            'form' => $form,
            'selectedFicheFrais' => $selectedFicheFrais,
            'ligneFraisForfait' => $ligneFraisForfait,
            'ligneFraisHorsForfait' => $ligneFraisHorsForfait,
        ]);
    }

    #[Route('/new', name: 'app_fiche_frais_new', methods: ['GET', 'POST'])]
    public function new(Request $request): Response
    {
        $ficheFrais = new FicheFrais();
        $form = $this->createForm(FicheFraisType::class, $ficheFrais);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // Lier la fiche à l'utilisateur connecté
            $ficheFrais->setUser($this->getUser());
            $this->entityManager->persist($ficheFrais);
            $this->entityManager->flush();

            $this->addFlash('success', 'Fiche de frais créée avec succès.');
            return $this->redirectToRoute('app_fiche_frais_index');
        }

        return $this->render('fiche_frais/new.html.twig', [
            'fiche_frais' => $ficheFrais,
            'form' => $form->createView(),
        ]);
    }

    #[Route('/{id}', name: 'app_fiche_frais_show', methods: ['GET'])]
    public function show(FicheFrais $ficheFrais): Response
    {
        return $this->render('fiche_frais/show.html.twig', [
            'fiche_frais' => $ficheFrais,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_fiche_frais_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, FicheFrais $ficheFrais): Response
    {
        $form = $this->createForm(FicheFraisType::class, $ficheFrais);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->entityManager->flush();

            $this->addFlash('success', 'Fiche de frais modifiée avec succès.');
            return $this->redirectToRoute('app_fiche_frais_index');
        }

        return $this->render('fiche_frais/edit.html.twig', [
            'fiche_frais' => $ficheFrais,
            'form' => $form->createView(),
        ]);
    }

    #[Route('/{id}', name: 'app_fiche_frais_delete', methods: ['POST'])]
    public function delete(Request $request, FicheFrais $ficheFrais): Response
    {
        // Vérification CSRF pour la suppression
        if ($this->isCsrfTokenValid('delete' . $ficheFrais->getId(), $request->request->get('_token'))) {
            $this->entityManager->remove($ficheFrais);
            $this->entityManager->flush();

            $this->addFlash('success', 'Fiche de frais supprimée avec succès.');
        } else {
            $this->addFlash('error', 'Token CSRF invalide.');
        }

        return $this->redirectToRoute('app_fiche_frais_index');
    }

    public function cloturerFichesFrais(): void
    {
        // Récupérer toutes les fiches de frais
        $ficheFraisList = $this->ficheFraisRepository->findAll();

        // Obtenir la date actuelle
        $currentDate = new DateTime();
        $currentMonth = $currentDate->format('m/Y');

        foreach ($ficheFraisList as $fiche) {
            if ($fiche->getMois()->format('m/Y') < $currentMonth && $fiche->getEtat()->getLibelle() !== 'CL') {
                $etatCloturee = $this->entityManager->getRepository(Etat::class)->findOneBy(['libelle' => 'CL']);

                if ($etatCloturee) {
                    $fiche->setEtat($etatCloturee);
                    $fiche->setDateModif(new DateTime());
                    $this->entityManager->flush();
                }
            }
        }
    }
}

templates/fiche_frais/_delete_form.html.twig
<form method="post" action="{{ path('app_fiche_frais_delete', {'id': fiche_frai.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ fiche_frai.id) }}">
    <button class="btn">Delete</button>
</form>

templates/fiche_frais/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/fiche_frais/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit FicheFrais{% endblock %}

{% block body %}
    <h1 class="text-2xl font-bold mb-6">Edit Fiche Frais</h1>

    <div class="max-w-4xl mx-auto bg-white shadow-md rounded-lg p-6">
        <h2 class="text-xl font-semibold mb-4">Modifier la Fiche de Frais</h2>

        <!-- Section pour le mois -->
        <div class="mb-4">
            <h3 class="font-semibold text-lg mb-2">Mois</h3>
            {{ form_row(form.mois, {'attr': {'class': 'border rounded-lg p-2 w-full'}}) }}
        </div>

        <!-- Section pour le nombre de justificatifs -->
        <div class="mb-4">
            <h3 class="font-semibold text-lg mb-2">Nombre de Justificatifs</h3>
            {{ form_row(form.nbJustificatifs, {'attr': {'class': 'border rounded-lg p-2 w-full'}}) }}
        </div>

        <!-- Section pour le montant valid -->
        <div class="mb-4">
            <h3 class="font-semibold text-lg mb-2">Montant Valid</h3>
            {{ form_row(form.montantValid, {'attr': {'class': 'border rounded-lg p-2 w-full'}}) }}
        </div>

        <!-- Section pour la date de modification -->
        <div class="mb-4">
            <h3 class="font-semibold text-lg mb-2">Date de Modification</h3>
            {{ form_row(form.dateModif, {'attr': {'class': 'border rounded-lg p-2 w-full'}}) }}
        </div>

        <div class="mt-6">
            <button type="submit" class="bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded">
                Update
            </button>
            <a href="{{ path('app_fiche_frais_index') }}" class="inline-block bg-gray-300 hover:bg-gray-400 text-gray-700 font-bold py-2 px-4 rounded ml-4">Back to list</a>
            <a href="{{ path('app_fiche_frais_delete', {'id': fiche_frais.id}) }}" class="inline-block bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded ml-2">Delete</a>
        </div>
    </div>
{% endblock %}

templates/fiche_frais/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Bienvenue sur GSB Frais{% endblock %}

{% block body %}
    <div class="container mx-auto px-6 py-10">

        <div class="bg-blue-600 p-6 rounded-lg shadow-lg text-white">
            <h1 class="text-2xl font-semibold mb-4 text-center">Rechercher une fiche de frais</h1>
            {# Utilisation de data-turbo-frame pour soumettre le formulaire dans un frame turbo spécifique #}
            {{ form_start(form, {'attr': {'class': 'flex items-center flex-col sm:flex-row', 'data-turbo-frame': 'the_frame_fiche'}}) }}
            <div class="flex-grow mr-4 mb-4 sm:mb-0">
                {{ form_row(form.mois, {'attr': {'class': 'w-full bg-blue-50 text-gray-700 border-blue-400 rounded-md shadow-sm focus:ring-blue-500 focus:border-blue-500'}}) }}
            </div>
            <button type="submit"
                    class="w-full sm:w-auto px-6 py-2 bg-blue-700 text-white font-medium rounded-md shadow-md hover:bg-blue-800 transition-colors duration-300 ease-in-out">
                Rechercher
            </button>
            {{ form_end(form) }}
        </div>

        {# Turbo Frame pour la fiche de frais sélectionnée #}
        <turbo-frame id="the_frame_fiche">
            {% if selectedFicheFrais is not null %}
                <div class="mt-8 bg-white p-6 border border-blue-200 rounded-lg shadow-lg">
                    <h2 class="text-2xl font-semibold text-blue-600 mb-6">Fiche de frais - {{ selectedFicheFrais.mois|date('m/Y') }}</h2>
                    <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 mb-6">
                        <div>
                            <span class="block text-gray-500 font-medium">État :</span>
                            <span class="text-gray-900">{{ selectedFicheFrais.etat.libelle }}</span>
                        </div>
                        <div>
                            <span class="block text-gray-500 font-medium">Montant validé :</span>
                            <span class="text-gray-900">{{ selectedFicheFrais.montantValid|number_format(2, ',', ' ') }} €</span>
                        </div>
                        <div>
                            <span class="block text-gray-500 font-medium">Date de modification :</span>
                            <span class="text-gray-900">{{ selectedFicheFrais.dateModif|date('d/m/Y') }}</span>
                        </div>
                    </div>
                </div>

                <div class="mt-8 bg-white p-6 border border-blue-200 rounded-lg shadow-lg">
                    <h3 class="text-xl font-semibold text-blue-600 mb-4">Frais Forfaitisés</h3>
                    <table class="w-full text-left border-collapse">
                        <thead>
                        <tr>
                            <th class="border-b py-2 text-gray-600">Type</th>
                            <th class="border-b py-2 text-gray-600 text-right">Quantité</th>
                            <th class="border-b py-2 text-gray-600 text-right">Montant</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for ligneFraisForfait in selectedFicheFrais.lignefraisforfaits %}
                            <tr class="hover:bg-blue-100">
                                <td class="py-2 border-b">{{ ligneFraisForfait.fraisForfaits.libelle }}</td>
                                <td class="py-2 border-b text-right">{{ ligneFraisForfait.quantite }}</td>
                                <td class="py-2 border-b text-right">{{ ligneFraisForfait.montant|number_format(2, ',', ' ') }} €</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>

                <div class="mt-8 bg-white p-6 border border-blue-200 rounded-lg shadow-lg">
                    <h3 class="text-xl font-semibold text-blue-600 mb-4">Frais Hors Forfaitisés</h3>
                    <table class="w-full text-left border-collapse">
                        <thead>
                        <tr>
                            <th class="border-b py-2 text-gray-600">Description</th>
                            <th class="border-b py-2 text-gray-600 text-right">Montant</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for ligneFraisHorsForfait in selectedFicheFrais.lignesfraishorsforfait %}
                            <tr class="hover:bg-blue-100">
                                <td class="py-2 border-b">{{ ligneFraisHorsForfait.libelle }}</td>
                                <td class="py-2 border-b text-right">{{ ligneFraisHorsForfait.montant|number_format(2, ',', ' ') }} €</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            {% else %}
                <div class="mt-8 text-center">
                    <p class="text-white">Veuillez sélectionner un mois pour voir la fiche correspondante.</p>
                </div>
            {% endif %}
        </turbo-frame>
    </div>
{% endblock %}

templates/fiche_frais/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New FicheFrais{% endblock %}

{% block body %}
    <h1>Create new FicheFrais</h1>

    {{ include('fiche_frais/_form.html.twig') }}

    <a href="{{ path('app_fiche_frais_index') }}">back to list</a>
{% endblock %}

templates/fiche_frais/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Fiche Frais{% endblock %}

{% block body %}
    <h1 class="text-2xl font-bold mb-6"></h1>

    <div class="max-w-4xl mx-auto bg-white shadow-md rounded-lg p-6">
        <h2 class="text-xl font-semibold mb-4">Détails de la Fiche de Frais</h2>
        <div class="overflow-x-auto">
            <table class="min-w-full bg-white border border-gray-300">
                <tbody class="text-gray-600">
                <tr class="border-b">
                    <th class="py-2 px-4 text-left">Id</th>
                    <td class="py-2 px-4">{{ fiche_frais.id }}</td>
                </tr>
                <tr class="border-b">
                    <th class="py-2 px-4 text-left">Mois</th>
                    <td class="py-2 px-4">{{ fiche_frais.mois ? fiche_frais.mois|date('Y-m-d') : '' }}</td>
                </tr>
                <tr class="border-b">
                    <th class="py-2 px-4 text-left">Nb Justificatifs</th>
                    <td class="py-2 px-4">{{ fiche_frais.nbJustificatifs }}</td>
                </tr>
                <tr class="border-b">
                    <th class="py-2 px-4 text-left">Montant Valid</th>
                    <td class="py-2 px-4">{{ fiche_frais.montantValid }}</td>
                </tr>
                <tr class="border-b">
                    <th class="py-2 px-4 text-left">Date Modif</th>
                    <td class="py-2 px-4">{{ fiche_frais.dateModif ? fiche_frais.dateModif|date('Y-m-d H:i:s') : '' }}</td>
                </tr>
                </tbody>
            </table>
        </div>

        <div class="mt-6">
            <a href="{{ path('app_fiche_frais_index') }}" class="inline-block bg-gray-300 hover:bg-gray-400 text-gray-700 font-bold py-2 px-4 rounded">Back to list</a>
            <a href="{{ path('app_fiche_frais_edit', {'id': fiche_frais.id}) }}" class="inline-block bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded ml-2">Edit</a>
            <a href="{{ path('app_fiche_frais_delete', {'id': fiche_frais.id}) }}" class="inline-block bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded ml-2">Delete</a>
        </div>
    </div>
{% endblock %}

templates/fiche_frais/top_visiteurs.html.twig
{% extends 'base.html.twig' %}

{% block title %}Top Visiteurs{% endblock %}

{% block body %}
    <h1>Top 3 Visiteurs Médicaux</h1>

    <form method="post">
        {{ form_start(form) }}
        {{ form_row(form.mois) }}
        <button type="submit">Voir</button>
        {{ form_end(form) }}
    </form>

    {% if topVisitors is not empty %}
        <h2>Top 3 des visiteurs avec les frais validés les plus élevés</h2>
        <ul>
            {% for visitor in topVisitors %}
                <li>
                    {{ visitor.user.username }} - Frais validés : {{ visitor.totalFrais }}
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>Aucun visiteur trouvé pour ce mois.</p>
    {% endif %}
{% endblock %}